version: 2.1

orbs:
  windows: circleci/windows@5.0
  general-platform-helpers: okta/general-platform-helpers@1.9
  platform-helpers: okta/platform-helpers@1
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  reversing-labs:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    resource_class: large
    steps:
      - run:
          name: Checkout Source Code
          command: |
            git --version
            rm -rf .git || true
            git init .
            git remote add origin https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git
            git fetch --depth=1 origin $CIRCLE_SHA1
            git checkout --force $CIRCLE_SHA1

      - run:
          name: Verify .NET SDK Installation
          command: dotnet --version

      - run:
          name: Build Release Binaries for Security Scan
          command: |
            # Build all projects
            dotnet build ./src/Okta.Sdk.Abstractions/Okta.Sdk.Abstractions.csproj --configuration Release
            dotnet build ./src/Okta.Sdk.Abstractions.UnitTests/Okta.Sdk.Abstractions.UnitTests.csproj --configuration Release

      - run:
          name: Setup Python Virtual Environment
          command: |
            apt-get update
            apt-get install -y curl python3 python3-pip python3-venv unzip
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip

      - run:
          name: Download ReversingLabs Scanner
          command: |
            curl https://dso-resources.oktasecurity.com/scanner \
              -H "x-api-key: $DSO_RLSECURE_TOKEN" \
              --output rl_wrapper-0.0.2+35ababa-py3-none-any.whl

      - run:
          name: Install ReversingLabs Wrapper
          command: |
            source venv/bin/activate
            pip install ./rl_wrapper-0.0.2+35ababa-py3-none-any.whl

      - aws-cli/setup:
          profile_name: default
          role_arn: $AWS_ARN
          region: us-east-1

      - run:
          name: Configure AWS Credentials
          command: >-
            eval "$(aws configure export-credentials --profile default --format env)" 2> /dev/null

      - run:
          name: Execute ReversingLabs Security Scan
          command: |
            source venv/bin/activate
            rl-wrapper \
              --artifact ${CIRCLE_WORKING_DIRECTORY/#\~/$HOME} \
              --name $CIRCLE_PROJECT_REPONAME\
              --version $CIRCLE_SHA1\
              --repository $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              --commit $CIRCLE_SHA1 \
              --build-env "circleci" \
              --suppress_output

  Build:
    executor:
      name: windows/default
    environment:
      CIRCLE_CI: True
    steps:
      - run:
          name: Checkout Source Code
          command: |
            git --version
            if (Test-Path .git) { Remove-Item -Recurse -Force .git }
            git init .
            git remote add origin https://github.com/$env:CIRCLE_PROJECT_USERNAME/$env:CIRCLE_PROJECT_REPONAME.git
            git fetch --depth=1 origin $env:CIRCLE_SHA1
            git checkout --force $env:CIRCLE_SHA1
      - run:
          name: Build and Test
          command: .\build.ps1 -Target Test
      - persist_to_workspace:
          root: ~/project
          paths:
            - src
            - .git
  
  snyk-scan:
    docker:
      - image: cimg/python:3.10
    steps:
      - attach_workspace:
          at: ~/project
      - general-platform-helpers/step-load-dependencies
      - general-platform-helpers/step-run-snyk-monitor:
          scan-all-projects: true
          skip-unresolved: false
          run-on-non-main: true
          detection-depth: 4

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  "Build and Security Scanning":
    jobs:
      - Build
      - reversing-labs:
          context:
            - static-analysis
          name: ReversingLabs Binary Scan
          requires:
            - Build
      - snyk-scan:
          name: Snyk Dependency Scan
          context:
            - static-analysis
          requires:
            - Build
      - platform-helpers/job-semgrep-scan:
          context:
            - static-analysis
          name: Semgrep Code Analysis
          requires:
            - Build
